### ISSUE TITLE
+entityForName: nil is not a legal NSPersistentStoreCoordinator for searching for entity name 'CDUser'

### ISSUE THREAD

**Issue by failynsedik** [chat-sdk/chat-sdk-ios#422] opened 2019-12-26 04:28 UTC
1. **Is the bug present in the demo Chat SDK project?**
Not sure because crash is intermittent.

2. **What modifications have you made to the Chat SDK?**
Feature customizations which can be seen at https://github.com/failynsedik/chat-sdk-ios.

3. **iOS Version? Device or simulator?**
iOS 12.4.4
iPhone 6 device

4. **Steps taken to reproduce the problem:**
Not sure myself, but this is what I found on stackoverflow (https://stackoverflow.com/questions/38698235/nil-is-not-a-legal-nspersistentstorecoordinator-for-searching-for-entity-name-g).

` - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {  
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{ 
        // your CoreData operation here
    }
    // ...
}`

5. **Expected result:**
No crash.

6. **Actual result:**
App is crashing.

7. **Comments:**
I filed this issue because of the following findings:
https://stackoverflow.com/questions/38698235/nil-is-not-a-legal-nspersistentstorecoordinator-for-searching-for-entity-name-g
https://stackoverflow.com/questions/20472465/entityforname-nil-is-not-a-legal-nsmanagedobjectcontext-parameter-searching-fo

**Comment by failynsedik** [comment] 2019-12-26 04:34
This is the stack trace.
<img width="739" alt="Screen Shot 2019-12-26 at 12 33 20 PM" src="https://user-images.githubusercontent.com/52100901/71458066-034eb680-27dc-11ea-8c70-057912f01ddf.png">

**Comment by failynsedik** [comment] 2020-02-17 07:43
Hi @bensmiley. Kindly want to ask if you have an idea for the above crash? Thank you. 🙏🏼

**Comment by ganico** [comment] 2020-10-21 05:56
> Hi @bensmiley. Kindly want to ask if you have an idea for the above crash? Thank you. 🙏🏼

did you manage to fix this? @failynsedik

**Comment by bensmiley** [comment] 2021-06-24 11:31
This should be fixed in the latest version. It was caused by accessing CoreData on the wrong thread.

**Closed by bensmiley** 2021-06-24 11:31 UTC
