### ISSUE TITLE
Pod installation issue "target has transitive dependencies"

### ISSUE THREAD

**Issue by maizer999** [chat-sdk/chat-sdk-ios#11] opened 2017-02-09 12:37 UTC
Dear When i tried to install pod for the chat on my project i get bellow error

[!] The 'Pods-Chat' target has transitive dependencies that include static binaries: (/Users/../Pods/Google/Frameworks/GGLCore.framework, /Users/../Pods/Google/Frameworks/GGLSignIn.framework, and /Users/../Pods/TwitterKit/TwitterKit.framework)

**Comment by bensmiley** [comment] 2017-02-09 14:48
Hi,

Could you provide me with a copy of your Podfile?

Thanks,

Ben

**Comment by simonsmiley64** [comment] 2017-02-12 22:49
Hi @maizer999,

Are you trying to add Chat SDK to a Swift project?

I found a potential guide [here](https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md) that might help your problem. 

If you could post more details on your project and podfile we can identify the problem more easily.

Simon

**Comment by jimijon** [comment] 2017-02-18 21:47
Same problem here.

`source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9'

workspace 'TwoBitTrader'
project   'TwoBitTrader'

#inhibit_all_warnings!
use_frameworks!

target 'TwoBitTrader' do
  pod 'Alamofire'
  pod 'Sync'
  pod 'PKHUD_Swift_3'
  pod 'SwiftyJSON'
  pod 'Siren'
  pod 'Groot'
  pod 'Charts'
  pod 'BigBoard', :path => '~/Documents/Development/BigBoard'
  pod "ChatSDK", :path => "."
#  pod "ChatSDKModules/Backendless", :path => "./ChatSDKModules"
  pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
pod 'PopupDialog', '~> 0.5'
pod 'Bolts'
#pod 'Webhose', :git => 'https://github.com/tiagomartinho/webhose-cocoa'
#pod 'Fabric'
#pod 'TwitterKit'

end`

error:

[!] The 'Pods-TwoBitTrader' target has transitive dependencies that include static binaries: (/Users/James/Documents/Development/INDX420/Pods/Google/Frameworks/GGLCore.framework, /Users/James/Documents/Development/INDX420/Pods/Google/Frameworks/GGLSignIn.framework, and /Users/James/Documents/Development/INDX420/Pods/TwitterKit/TwitterKit.framework)

**Comment by bensmiley** [comment] 2017-02-18 21:51
This is because you're using the use_frameworks! flag. Some of the dependencies of the Chat SDK won't work if that flag is enabled - from memory they are the Google and Twitter frameworks. You should either remove the use_frameworks! flag or try to implement the workaround detailed [here](https://github.com/googlemaps/google-maps-ios-utils/issues/23).

**Comment by jimijon** [comment] 2017-02-18 22:07
Well I can’t take off that flag as I have a dozen frameworks.

I can copy the Google code over, but how do I get around the cocoapods error?

**Comment by jimijon** [comment] 2017-02-19 12:52
Ok,,, got everything.... I think but now it just can't find the FBCore header. I looked at all my search path headers and frameworks... all looks Ok.   Any thoughts about this?

**Comment by jimijon** [comment] 2017-02-19 16:46
Ok, removed FB from the pod spec, and did manual install. That worked. But now I get a FirebaseAnalytics issue. argh.

**Comment by bensmiley** [comment] 2017-02-20 01:10
What kind of error are you getting?

**Comment by jimijon** [comment] 2017-02-25 15:38
There are way too many dependency issues for me at this point. I need to get a beta out, so, went with a simple Firebase Chat controller. All the pods worked and I was able to get Chat working good enough for demo purposes. I would like to later, use your SDK, but we will see. I will probably wait until ALL frameworks work with pod use-Frameworks! flag set.

**Comment by bensmiley** [comment] 2017-03-03 00:02
I managed to fix this issue. In the next few days we will release a new version which moves the social login dependencies to a separate pod. That will make it much easier to remove them if they are not needed. It will also enable `use_frameworks!`. 

I'd check the repository early next week to get the new version.

**Comment by jimijon** [comment] 2017-03-03 17:49
Great news and great work. I will look forward to it next week.

**Comment by jimijon** [comment] 2017-03-16 19:34
Any progress?

**Comment by bensmiley** [comment] 2017-03-21 02:58
You should checkout the `use_frameworks_beta_1` branch. I found that the issues were caused by the way that Firebase have setup their pods. 

The solution was to compile the Firebase frameworks manually using Carthage and then add them using the `vendored_framework` attribute in the podfile. 

You'll see that in the new version, we have had to change the project structure a little - we broke up the core library into separate pods rather than using subspecs. You'll have to rename your imports accordingly. 

Currently, the modules don't work with this version. We will need to do some additional work to get them supported. We also split the social login into a separate pod.

**Comment by jimijon** [comment] 2017-03-21 13:17
Sounds like good progress. I still have time as I am deep into working on other features and also trying to get my little app out the door that doesn't use any chat. I will however, be monitoring this as I expect to come back to some serious chat work in about a month.  Thanks for the work.

**Comment by jimijon** [comment] 2017-04-10 15:52
Ok - I am coming back to this and I noticed you now have 3 use_frameworks branches. Which one are you recommending now?

**Comment by bensmiley** [comment] 2017-04-11 04:13
I would recommend `use_frameworks_beta_x` where `x` is the highest number. Currently 1 but soon to be 2.

**Comment by bensmiley** [comment] 2017-04-26 08:20
We have now merged the use_frameworks version of the project with the master branch so I'm closing this issue. If you need to use the old non-frameworks version of the project you can by using the `master_no_frameworks` branch.

**Closed by bensmiley** 2017-04-26 08:20 UTC
Labels: help wanted
