### ISSUE TITLE
Shows zero threads while getting list of private threads.

### ISSUE THREAD

**Issue by softcraftgit** [chat-sdk/chat-sdk-ios#187] opened 2018-01-11 12:35 UTC
I login with the following code:

[NM.auth authenticate:[BAccountDetails username:strUserName password:strUserPwd]].thenOnMain(^id(id<PUser> user)
 {
}

While trying to get private threads with the following code, I am getting zero threads in the array.

NSArray * threads = [NM.core threadsWithType:bThreadFilterPrivate];

**Comment by bensmiley** [comment] 2018-01-11 12:40
Does the user have some threads associated with them? Are you seeing some threads in the conversations screen?

**Comment by softcraftgit** [comment] 2018-01-11 12:45
Yes we have created private threads and the same is working fine with Android.

**Comment by bensmiley** [comment] 2018-01-24 19:29
The only situation I can see when this wouldn't work is if the `NM.core().currentUserModel()` is `Nil`. In which case the app hasn't completed authentication. I think this could have been caused by a bug which has been fixed in 4.3.16. See #193.

**Closed by bensmiley** 2018-01-24 19:29 UTC
